### ISSUE TITLE
asr_raw.php - authentication failed 3302 - vop.baidu.com/pro_api

### ISSUE THREAD

**Issue by Jack-JieKe** [Baidu-AIP/speech-demo#6]
demo not working, any suggestions ?

1. 语音识别极速版 payment opened
![Screenshot 2019-05-21 11 45 51](https://user-images.githubusercontent.com/50856170/58067020-59aca480-7bbe-11e9-9844-9ed79e7f1d6a.png)

2. OK: 收费版打开以下信息 打开注释的话请填写自己申请的appkey appSecret ，并在网页中开通极速版.

3. Token return successfully.

4. Token scope OK: 
"scope":"brain_enhanced_asr audio_voice_assistant_get audio_tts_post public brain_all_scope wise_adapt lebo_resource_base lightservice_public hetu_basic lightcms_map_poi kaidian_kaidian ApsMisTest_Test\u6743\u9650 vis-classify_flower lpq_\u5f00\u653e cop_helloScope ApsMis_fangdi_permission smartapp_snsapi_base iop_autocar oauth_tp_app smartapp_smart_game_openapi oauth_sessionkey smartapp_swanid_verify smartapp_opensource_openapi smartapp_opensource_recapi"

4. "err_msg":"authentication failed.","err_no":3302,"sn":"****"

**Comment by authorfu** [comment]
scope中没有极速版的
