### ISSUE TITLE
为什么使用百度语音tts合成的，再通过ASR转写失败

### ISSUE THREAD

**Issue by tinet-hanyang** [Baidu-AIP/speech-demo#7]

**Comment by tinet-hanyang** [comment]
![image](https://user-images.githubusercontent.com/49931588/63138698-ffc94880-c00d-11e9-9a23-94631b334d20.png)

**Comment by authorfu** [comment]
有问题可以到ai.baidu.com底部查找qq群提问。
这里仅讨论demo的代码问题
